name: Test AWS OIDC
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  identity:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - run: aws sts get-caller-identity
